# Generated by Django 6.0 on 2025-12-25 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='days_to_receive',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='installments',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price_sold',
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='hourly_labor_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.sale'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.CharField(choices=[('REVENUE', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='Consumidor Final', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
