# Generated by Django 6.0 on 2025-12-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financialtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Telefone/WhatsApp', max_length=20, null=True),
        ),
    ]
