# Generated by Django 6.0 on 2025-12-26 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_sale_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pago/Recebido'), ('PENDING', 'Pendente/Agendado')], default='PAID', max_length=10),
        ),
    ]
