# Generated by Django 6.0 on 2025-12-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialtransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
