# Generated by Django 6.0 on 2025-12-24 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('UN', 'UN'), ('MT', 'MT'), ('KG', 'KG'), ('LT', 'LT')], max_length=4)),
                ('current_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, help_text='Fornecedor', max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, help_text='Valor do Frete', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total Produtos + Frete', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('labor_time_minutes', models.IntegerField(default=0)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Preço na Nota (sem frete)', max_digits=10)),
                ('effective_unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Custo Final (Com Frete)', max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_history', to='inventory.material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
        ),
    ]
